server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
          - Path=/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
