server:
  port: 8080

spring:
  application:
    name: gateway-server
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/eurekadb
    username: postgres
    password: Thaisebruno10
    driverClassName: org.postgresql.Driver
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/**
        filters:
        - AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: xx22xxxxxxxxxxxxxxxY
  token:
    validity: 864000000
    prefix: Bearer