server:
  port: 8081

spring:
  application:
    name: product-service
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/eurekadb
    username: postgres
    password: Thaisebruno10
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    hostname: localhost


